# Generated by Django 4.2.4 on 2023-09-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
