# Generated by Django 4.2.6 on 2023-11-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancle_order', 'can cancle order')]},
        ),
    ]
